[workspace]
members = ["twine-core", "twine-bridge"]
resolver = "3"

[profile.release]
opt-level = 3
lto = "fat"
codegen-units = 1
debug = false
strip = "debuginfo"

[workspace.package]
version = "0.2.1"
edition = "2024"
publish = false

[workspace.lints.clippy]
cargo = "warn"
pedantic = "warn"
mod_module_files = "warn"
