name: Cargo Audit

on:
  workflow_call:

permissions:
  contents: read

jobs:
  cargo-audit:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7
      - name: Install cargo-audit
        uses: taiki-e/install-action@v2
        with:
          tool: cargo-audit
      - name: Audit Rust dependencies
        run: cargo audit
